name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Code checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 1.24.11

      - name: Build release binaries
        env:
          CGO_ENABLED: 0
          VERSION: ${{ github.ref_name }}
        run: |
          GOARCH=amd64 go build -o dist/royalwings_linux_amd64 -v -trimpath -ldflags="-s -w -X github.com/royalwings/system.Version=${VERSION:1}" github.com/royalwings
          chmod 755 dist/royalwings_linux_amd64
          GOARCH=arm64 go build -o dist/royalwings_linux_arm64 -v -trimpath -ldflags="-s -w -X github.com/royalwings/system.Version=${VERSION:1}" github.com/royalwings
          chmod 755 dist/royalwings_linux_arm64

      - name: Create release branch
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          BRANCH=release/${{ env.VERSION }}
          git config --local user.email "ci@royalwings.local"
          git config --local user.name "RoyalWings CI"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/var Version = \".*\"/var Version = \"${VERSION:1}\"/" system/const.go
          git add system/const.go
          git commit -m "ci(release): bump version"
          git push

      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
          files: |
            dist/*
